// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UiCodePilot
{
    internal sealed partial class Vsix
    {
        public const string Id = "UiCodePilot.1851f478-0b9a-404d-9907-3b0735308caf";
        public const string Name = "UiCodePilot";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
